name: Retweet
description: Suggest a retweet of another tweet
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this suggestion! Once submitted we will review it and publish it if everything is okay.
  - type: input
    id: description
    attributes:
      label: Content Description
      description: What is this tweet about? Please describe the purpose in detail. This part will not be part of the tweet!
    validations:
      required: true
  - type: input
    id: tweetID
    attributes:
      label: Retweet
      description: Add the full URL of the tweet to retweet
      placeholder: https://twitter.com/mozilla/status/1153315573507473409
    validations:
      required: true
